export const EVENT_REGISTERED = 'EVENT_REGISTERED';
export const EVENT_UNREGISTERED = 'EVENT_UNREGISTERED';
export const EVENT_NOT_FOUND = 'EVENT_NOT_FOUND';
export const HANDLER_UPDATED = 'HANDLER_UPDATED';
export const HANDLER_NOT_FOUND = 'HANDLER_NOT_FOUND';
export const EVENT_DELETED = 'EVENT_DELETED';